import './globals.scss';
// import { Inter } from 'next/font/google';
import Link from 'next/link';
import styles from './navigator.module.scss';

// export const metadata = {
//   title: { default: 'Next Example | UpLeveled', template: '%s | UpLeveled' },
//   description: 'Generated by create next app',
// };

export const metadata = {
  title: {
    default: "Your regional farmer | Zum Bauern z'Huber",
    template: " %s | Zum Bauern z'Huber",
  },
  description:
    'Choose your agricultural products, from your direct marketing farmer nearby and pick them up within the same day',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className={styles.navigator}>
          <Link href="/">home</Link>
          <br />
          <Link href="/products-page">products</Link>
          <br />
          <Link href="/about">about</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
